name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: copy id_rsa.pub
      run: |
        mkdir ~/.ssh
        echo ${{secrets.ID_RSA_PUB}} > ~/.ssh/id_rsa.pub
    - name: check id_rsa.pub
      run: cat ~/.ssh/id_rsa.pub
    - name: remote exec
      run: ssh -i id_rsa ${{secrets.USER}}@${{secrets.SERVER_IP}} "echo test > test"
