name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: copy id_rsa
      run: |
        echo "${{secrets.ID_RSA}}" > id_rsa
        chmod 600 id_rsa
    - name: remote exec
      run: ssh -o StrictHostKeyChecking=no -i id_rsa -vvv ${{secrets.USER}}@${{secrets.SERVER_IP}} \
        "cd pbl-application; git pull; ./gradlew build -x test; ${{secrets.RESTART_SERVER}}"
